get_tweets.settings:
  type: config_object
  label: 'Get Tweets settings'
  mapping:
    import:
      type: boolean
      label: 'Import tweets'
    queries:
      type: sequence
      label: 'Hashtags and User mentions for import'
      sequence:
        type: mapping
        label: 'Query'
        mapping:
          query:
            type: string
            label: 'Query'
          endpoint:
            type: string
            label: 'Endpoint'
          parameter:
            type: string
            label: 'Parameter'
    count:
      type: integer
      label: 'Tweets count'
    expire:
      type: integer
      label: 'Expire date for tweets'
    consumer_key:
      type: string
      label: 'OAuth Consumer key'
    consumer_secret:
      type: string
      label: 'OAuth Consumer secret'
